"""Write packaging/notices/qt-third-party.txt from Qt's own attribution files.

Qt keeps a qt_attribution.json next to every third-party library it includes.
This fetches them, and the license files they point to, for the Qt version the
app ships with (PySide6's version), from Qt's GitHub mirrors.

Run it again after upgrading PySide6:
    python scripts/update_qt_notices.py

Components that can't be in the Windows build of the modules the app uses
(Wayland, X11, macOS, Android, WebAssembly, and test or build tools) are left
out. Everything else is kept, so the list errs on the side of crediting too much.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from importlib.metadata import version
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "packaging" / "notices" / "qt-third-party.txt"
# QtCore, QtGui, QtWidgets, QtNetwork (qtbase), QtSvg, and the image format plugins.
REPOS = ("qtbase", "qtsvg", "qtimageformats")
SKIP = (
    "wayland",
    "xcb",
    "android",
    "cocoa",
    "wasm",
    "gradle",
    "testlib",
    "testinternal",
    "tests/",
    "examples/",
    "cmake/",
    "util/",
    "forkfd",  # Unix only
)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "taste-engine-notices"})
    with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310 (fixed hosts)
        return response.read()


def attribution_paths(repo: str, tag: str) -> list[str]:
    tree = json.loads(fetch(f"https://api.github.com/repos/qt/{repo}/git/trees/{tag}?recursive=1"))
    return sorted(
        item["path"]
        for item in tree["tree"]
        if item["path"].endswith("qt_attribution.json")
        and not any(part in item["path"] for part in SKIP)
    )


def license_files(entry: dict) -> list[str]:
    files = entry.get("LicenseFiles") or entry.get("LicenseFile") or []
    return [files] if isinstance(files, str) else list(files)


def copyright_text(entry: dict) -> str:
    value = entry.get("Copyright") or ""
    return "\n".join(value) if isinstance(value, list) else value


def main() -> None:
    qt_version = version("PySide6")
    tag = f"v{qt_version}"
    sections = []
    for repo in REPOS:
        raw = f"https://raw.githubusercontent.com/qt/{repo}/{tag}"
        for path in attribution_paths(repo, tag):
            data = json.loads(fetch(f"{raw}/{path}"), strict=False)  # some contain raw tabs
            for entry in data if isinstance(data, list) else [data]:
                parts = entry.get("QtParts") or ["libs"]
                if "libs" not in parts and "plugins" not in parts:
                    continue
                folder = PurePosixPath(path).parent
                texts = []
                for name in license_files(entry):
                    text = fetch(f"{raw}/{folder / name}").decode("utf-8", "replace").strip()
                    texts.append(text)
                header = [
                    f"{entry.get('Name', entry.get('Id', '?'))} ({repo})",
                    f"Version: {entry.get('Version', 'not stated')}",
                    f"License: {entry.get('License', '')} ({entry.get('LicenseId', '')})",
                    f"Homepage: {entry.get('Homepage', '')}",
                ]
                copyright_lines = copyright_text(entry)
                if copyright_lines:
                    header.append(f"Copyright:\n{copyright_lines}")
                sections.append("\n".join(header) + ("\n\n" + "\n\n".join(texts) if texts else ""))
                print(f"  {repo}: {entry.get('Name')}", file=sys.stderr)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rule = "\n\n" + "-" * 78 + "\n\n"
    intro = (
        f"Third-party components included in Qt {qt_version}, as listed by Qt's own\n"
        "attribution files (qtbase, qtsvg, qtimageformats). Generated by\n"
        "scripts/update_qt_notices.py.\n"
    )
    OUT.write_text(intro + rule + rule.join(sections) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(sections)} components")


if __name__ == "__main__":
    main()
